/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface BMoonCatsReaderContract
  extends Truffle.Contract<BMoonCatsReaderInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<BMoonCatsReaderInstance>;
}

type AllEvents = never;

export interface BMoonCatsReaderInstance extends Truffle.ContractInstance {
  getCatOwners(
    from: number | BN | string,
    size: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  methods: {
    getCatOwners(
      from: number | BN | string,
      size: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
