/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC165Contract } from "./ERC165";
import { ERC721Contract } from "./ERC721";
import { IERC165Contract } from "./IERC165";
import { IERC721Contract } from "./IERC721";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { INFTKEYMarketPlaceV1Contract } from "./INFTKEYMarketPlaceV1";
import { MigrationsContract } from "./Migrations";
import { NFTKEYMarketPlaceContract } from "./NFTKEYMarketPlace";
import { NFTKEYMarketPlaceV11Contract } from "./NFTKEYMarketPlaceV11";
import { NFTKEYMarketPlaceV1Contract } from "./NFTKEYMarketPlaceV1";
import { OwnableContract } from "./Ownable";
import { TestERC20Contract } from "./TestERC20";
import { TestERC721Contract } from "./TestERC721";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "INFTKEYMarketPlaceV1"): INFTKEYMarketPlaceV1Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "NFTKEYMarketPlace"): NFTKEYMarketPlaceContract;
      require(name: "NFTKEYMarketPlaceV1_1"): NFTKEYMarketPlaceV11Contract;
      require(name: "NFTKEYMarketPlaceV1"): NFTKEYMarketPlaceV1Contract;
      require(name: "Ownable"): OwnableContract;
      require(name: "TestERC20"): TestERC20Contract;
      require(name: "TestERC721"): TestERC721Contract;
    }
  }
}

export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export {
  INFTKEYMarketPlaceV1Contract,
  INFTKEYMarketPlaceV1Instance,
} from "./INFTKEYMarketPlaceV1";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  NFTKEYMarketPlaceContract,
  NFTKEYMarketPlaceInstance,
} from "./NFTKEYMarketPlace";
export {
  NFTKEYMarketPlaceV11Contract,
  NFTKEYMarketPlaceV11Instance,
} from "./NFTKEYMarketPlaceV11";
export {
  NFTKEYMarketPlaceV1Contract,
  NFTKEYMarketPlaceV1Instance,
} from "./NFTKEYMarketPlaceV1";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { TestERC20Contract, TestERC20Instance } from "./TestERC20";
export { TestERC721Contract, TestERC721Instance } from "./TestERC721";
