/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface MoonCatRescueContract
  extends Truffle.Contract<MoonCatRescueInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<MoonCatRescueInstance>;
}

type AllEvents = never;

export interface MoonCatRescueInstance extends Truffle.ContractInstance {
  adoptionOffers(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: boolean; 1: string; 2: string; 3: BN; 4: string }>;

  adoptionRequests(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: boolean; 1: string; 2: string; 3: BN }>;

  balanceOf(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<BN>;

  catNames(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  catOwners(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  decimals(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  imageGenerationCodeMD5(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  mode(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  name(txDetails?: Truffle.TransactionDetails): Promise<string>;

  pendingWithdrawals(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  remainingCats(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  remainingGenesisCats(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  rescueIndex(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  rescueOrder(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  searchSeed(txDetails?: Truffle.TransactionDetails): Promise<string>;

  symbol(txDetails?: Truffle.TransactionDetails): Promise<string>;

  totalSupply(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  methods: {
    adoptionOffers(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: boolean; 1: string; 2: string; 3: BN; 4: string }>;

    adoptionRequests(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: boolean; 1: string; 2: string; 3: BN }>;

    balanceOf(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    catNames(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    catOwners(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    decimals(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    imageGenerationCodeMD5(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    mode(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    name(txDetails?: Truffle.TransactionDetails): Promise<string>;

    pendingWithdrawals(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    remainingCats(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    remainingGenesisCats(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    rescueIndex(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    rescueOrder(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    searchSeed(txDetails?: Truffle.TransactionDetails): Promise<string>;

    symbol(txDetails?: Truffle.TransactionDetails): Promise<string>;

    totalSupply(txDetails?: Truffle.TransactionDetails): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
