/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface NFTKEYMarketPlaceV11Contract
  extends Truffle.Contract<NFTKEYMarketPlaceV11Instance> {
  "new"(
    erc721Name_: string,
    _erc721Address: string,
    _paymentTokenAddress: string,
    meta?: Truffle.TransactionDetails
  ): Promise<NFTKEYMarketPlaceV11Instance>;
}

export interface OwnershipTransferred {
  name: "OwnershipTransferred";
  args: {
    previousOwner: string;
    newOwner: string;
    0: string;
    1: string;
  };
}

export interface TokenBidAccepted {
  name: "TokenBidAccepted";
  args: {
    tokenId: BN;
    owner: string;
    bidder: string;
    total: BN;
    value: BN;
    fees: BN;
    0: BN;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
  };
}

export interface TokenBidEntered {
  name: "TokenBidEntered";
  args: {
    tokenId: BN;
    fromAddress: string;
    value: BN;
    0: BN;
    1: string;
    2: BN;
  };
}

export interface TokenBidWithdrawn {
  name: "TokenBidWithdrawn";
  args: {
    tokenId: BN;
    fromAddress: string;
    value: BN;
    0: BN;
    1: string;
    2: BN;
  };
}

export interface TokenBought {
  name: "TokenBought";
  args: {
    tokenId: BN;
    fromAddress: string;
    toAddress: string;
    total: BN;
    value: BN;
    fees: BN;
    0: BN;
    1: string;
    2: string;
    3: BN;
    4: BN;
    5: BN;
  };
}

export interface TokenDelisted {
  name: "TokenDelisted";
  args: {
    tokenId: BN;
    fromAddress: string;
    0: BN;
    1: string;
  };
}

export interface TokenListed {
  name: "TokenListed";
  args: {
    tokenId: BN;
    fromAddress: string;
    minValue: BN;
    0: BN;
    1: string;
    2: BN;
  };
}

type AllEvents =
  | OwnershipTransferred
  | TokenBidAccepted
  | TokenBidEntered
  | TokenBidWithdrawn
  | TokenBought
  | TokenDelisted
  | TokenListed;

export interface NFTKEYMarketPlaceV11Instance extends Truffle.ContractInstance {
  hasSharePercentageProposal(
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Returns the address of the current owner.
   */
  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  partnerAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  partnerSharePercentage(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  partnerSharePercentageProposal(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  renounceOwnership: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership: {
    (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newOwner: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-tokenAddress}.
   */
  tokenAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * See {INFTKEYMarketPlaceV1-paymentTokenAddress}.
   */
  paymentTokenAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * See {INFTKEYMarketPlaceV1-getTokenListing}.
   */
  getTokenListing(
    tokenId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    tokenId: BN;
    listingPrice: BN;
    seller: string;
    expireTimestamp: BN;
  }>;

  /**
   * See {INFTKEYMarketPlaceV1-getTokenListings}.
   */
  getTokenListings(
    from: number | BN | string,
    size: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    { tokenId: BN; listingPrice: BN; seller: string; expireTimestamp: BN }[]
  >;

  /**
   * See {INFTKEYMarketPlaceV1-getAllTokenListings}.
   */
  getAllTokenListings(
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    { tokenId: BN; listingPrice: BN; seller: string; expireTimestamp: BN }[]
  >;

  /**
   * See {INFTKEYMarketPlaceV1-getBidderTokenBid}.
   */
  getBidderTokenBid(
    tokenId: number | BN | string,
    bidder: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    tokenId: BN;
    bidPrice: BN;
    bidder: string;
    expireTimestamp: BN;
  }>;

  /**
   * See {INFTKEYMarketPlaceV1-getTokenBids}.
   */
  getTokenBids(
    tokenId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    { tokenId: BN; bidPrice: BN; bidder: string; expireTimestamp: BN }[]
  >;

  /**
   * See {INFTKEYMarketPlaceV1-getTokenHighestBid}.
   */
  getTokenHighestBid(
    tokenId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    tokenId: BN;
    bidPrice: BN;
    bidder: string;
    expireTimestamp: BN;
  }>;

  /**
   * See {INFTKEYMarketPlaceV1-getTokenHighestBids}.
   */
  getTokenHighestBids(
    from: number | BN | string,
    size: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    { tokenId: BN; bidPrice: BN; bidder: string; expireTimestamp: BN }[]
  >;

  /**
   * See {INFTKEYMarketPlaceV1-getAllTokenHighestBids}.
   */
  getAllTokenHighestBids(
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    { tokenId: BN; bidPrice: BN; bidder: string; expireTimestamp: BN }[]
  >;

  /**
   * See {INFTKEYMarketPlaceV1-listToken}. People can only list if listing is allowed The timestamp set needs to be in the allowed range Only token owner can list token Price must be higher than 0 This contract must be approved to transfer this token
   */
  listToken: {
    (
      tokenId: number | BN | string,
      value: number | BN | string,
      expireTimestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      tokenId: number | BN | string,
      value: number | BN | string,
      expireTimestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      tokenId: number | BN | string,
      value: number | BN | string,
      expireTimestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      tokenId: number | BN | string,
      value: number | BN | string,
      expireTimestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-delistToken}. msg.sender must be the seller of the listing record
   */
  delistToken: {
    (
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-buyToken}. Must have a valid listing msg.sender must not the owner of token msg.value must be at least sell price plus fees
   */
  buyToken: {
    (
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-enterBidForToken}. People can only enter bid if bid is allowed The timestamp set needs to be in the allowed range bid price > 0 must not be token owner must allow this contract to spend enough payment token
   */
  enterBidForToken: {
    (
      tokenId: number | BN | string,
      bidPrice: number | BN | string,
      expireTimestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      tokenId: number | BN | string,
      bidPrice: number | BN | string,
      expireTimestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      tokenId: number | BN | string,
      bidPrice: number | BN | string,
      expireTimestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      tokenId: number | BN | string,
      bidPrice: number | BN | string,
      expireTimestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-withdrawBidForToken}. There must be a bid exists remove this bid record
   */
  withdrawBidForToken: {
    (
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-acceptBidForToken}. Must be owner of this token Must have approved this contract to transfer token Must have a valid existing bid that matches the bidder address
   */
  acceptBidForToken: {
    (
      tokenId: number | BN | string,
      bidder: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      tokenId: number | BN | string,
      bidder: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      tokenId: number | BN | string,
      bidder: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      tokenId: number | BN | string,
      bidder: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-getInvalidListingCount}.
   */
  getInvalidListingCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * See {INFTKEYMarketPlaceV1-getInvalidBidCount}.
   */
  getInvalidBidCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * See {INFTKEYMarketPlaceV1-cleanAllInvalidListings}.
   */
  cleanAllInvalidListings: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-cleanAllInvalidBids}.
   */
  cleanAllInvalidBids: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-erc721Name}.
   */
  erc721Name(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * See {INFTKEYMarketPlaceV1-isListingAndBidEnabled}.
   */
  isListingAndBidEnabled(
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Enable to disable Bids and Listing
   */
  changeMarketplaceStatus: {
    (enabled: boolean, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      enabled: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      enabled: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      enabled: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-actionTimeOutRangeMin}.
   */
  actionTimeOutRangeMin(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * See {INFTKEYMarketPlaceV1-actionTimeOutRangeMax}.
   */
  actionTimeOutRangeMax(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * Change minimum listing and bid time range
   */
  changeMinActionTimeLimit: {
    (
      timeInSec: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      timeInSec: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      timeInSec: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      timeInSec: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Change maximum listing and bid time range
   */
  changeMaxActionTimeLimit: {
    (
      timeInSec: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      timeInSec: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      timeInSec: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      timeInSec: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * See {INFTKEYMarketPlaceV1-serviceFee}.
   */
  serviceFee(txDetails?: Truffle.TransactionDetails): Promise<{ 0: BN; 1: BN }>;

  /**
   * Change withdrawal fee percentage. If 1%, then input (1,100) If 0.5%, then input (5,1000)
   * @param feeBase_ Fraction of withdrawal fee base
   * @param feeFraction_ Fraction of withdrawal fee based on feeBase_
   */
  changeSeriveFee: {
    (
      feeFraction_: number | BN | string,
      feeBase_: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      feeFraction_: number | BN | string,
      feeBase_: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      feeFraction_: number | BN | string,
      feeBase_: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      feeFraction_: number | BN | string,
      feeBase_: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Set partner address and profit share
   * @param _partnerAddress Partner address
   * @param _partnerSharePercentage Fraction of withdrawal fee base
   */
  setPartnerAddressAndProfitShare: {
    (
      _partnerAddress: string,
      _partnerSharePercentage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _partnerAddress: string,
      _partnerSharePercentage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _partnerAddress: string,
      _partnerSharePercentage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _partnerAddress: string,
      _partnerSharePercentage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Change partner address
   * @param _partnerAddress Partner address Only partner can change their share address
   */
  changePartnerAddress: {
    (_partnerAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _partnerAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _partnerAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _partnerAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Propose partner share percentage
   * @param _partnerSharePercentage Partner proposed new share percentage
   */
  proposePartnerShareChange: {
    (
      _partnerSharePercentage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _partnerSharePercentage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _partnerSharePercentage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _partnerSharePercentage: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Accept partner share percentage proposal
   */
  acceptPartnerShareChange: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Reject partner share percentage proposal
   */
  rejectPartnerShareChange: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  methods: {
    hasSharePercentageProposal(
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Returns the address of the current owner.
     */
    owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    partnerAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

    partnerSharePercentage(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    partnerSharePercentageProposal(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership: {
      (newOwner: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newOwner: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-tokenAddress}.
     */
    tokenAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * See {INFTKEYMarketPlaceV1-paymentTokenAddress}.
     */
    paymentTokenAddress(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    /**
     * See {INFTKEYMarketPlaceV1-getTokenListing}.
     */
    getTokenListing(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      tokenId: BN;
      listingPrice: BN;
      seller: string;
      expireTimestamp: BN;
    }>;

    /**
     * See {INFTKEYMarketPlaceV1-getTokenListings}.
     */
    getTokenListings(
      from: number | BN | string,
      size: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      { tokenId: BN; listingPrice: BN; seller: string; expireTimestamp: BN }[]
    >;

    /**
     * See {INFTKEYMarketPlaceV1-getAllTokenListings}.
     */
    getAllTokenListings(
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      { tokenId: BN; listingPrice: BN; seller: string; expireTimestamp: BN }[]
    >;

    /**
     * See {INFTKEYMarketPlaceV1-getBidderTokenBid}.
     */
    getBidderTokenBid(
      tokenId: number | BN | string,
      bidder: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      tokenId: BN;
      bidPrice: BN;
      bidder: string;
      expireTimestamp: BN;
    }>;

    /**
     * See {INFTKEYMarketPlaceV1-getTokenBids}.
     */
    getTokenBids(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      { tokenId: BN; bidPrice: BN; bidder: string; expireTimestamp: BN }[]
    >;

    /**
     * See {INFTKEYMarketPlaceV1-getTokenHighestBid}.
     */
    getTokenHighestBid(
      tokenId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      tokenId: BN;
      bidPrice: BN;
      bidder: string;
      expireTimestamp: BN;
    }>;

    /**
     * See {INFTKEYMarketPlaceV1-getTokenHighestBids}.
     */
    getTokenHighestBids(
      from: number | BN | string,
      size: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      { tokenId: BN; bidPrice: BN; bidder: string; expireTimestamp: BN }[]
    >;

    /**
     * See {INFTKEYMarketPlaceV1-getAllTokenHighestBids}.
     */
    getAllTokenHighestBids(
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      { tokenId: BN; bidPrice: BN; bidder: string; expireTimestamp: BN }[]
    >;

    /**
     * See {INFTKEYMarketPlaceV1-listToken}. People can only list if listing is allowed The timestamp set needs to be in the allowed range Only token owner can list token Price must be higher than 0 This contract must be approved to transfer this token
     */
    listToken: {
      (
        tokenId: number | BN | string,
        value: number | BN | string,
        expireTimestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        tokenId: number | BN | string,
        value: number | BN | string,
        expireTimestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        tokenId: number | BN | string,
        value: number | BN | string,
        expireTimestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        tokenId: number | BN | string,
        value: number | BN | string,
        expireTimestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-delistToken}. msg.sender must be the seller of the listing record
     */
    delistToken: {
      (
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-buyToken}. Must have a valid listing msg.sender must not the owner of token msg.value must be at least sell price plus fees
     */
    buyToken: {
      (
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-enterBidForToken}. People can only enter bid if bid is allowed The timestamp set needs to be in the allowed range bid price > 0 must not be token owner must allow this contract to spend enough payment token
     */
    enterBidForToken: {
      (
        tokenId: number | BN | string,
        bidPrice: number | BN | string,
        expireTimestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        tokenId: number | BN | string,
        bidPrice: number | BN | string,
        expireTimestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        tokenId: number | BN | string,
        bidPrice: number | BN | string,
        expireTimestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        tokenId: number | BN | string,
        bidPrice: number | BN | string,
        expireTimestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-withdrawBidForToken}. There must be a bid exists remove this bid record
     */
    withdrawBidForToken: {
      (
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        tokenId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-acceptBidForToken}. Must be owner of this token Must have approved this contract to transfer token Must have a valid existing bid that matches the bidder address
     */
    acceptBidForToken: {
      (
        tokenId: number | BN | string,
        bidder: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        tokenId: number | BN | string,
        bidder: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        tokenId: number | BN | string,
        bidder: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        tokenId: number | BN | string,
        bidder: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-getInvalidListingCount}.
     */
    getInvalidListingCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * See {INFTKEYMarketPlaceV1-getInvalidBidCount}.
     */
    getInvalidBidCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * See {INFTKEYMarketPlaceV1-cleanAllInvalidListings}.
     */
    cleanAllInvalidListings: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-cleanAllInvalidBids}.
     */
    cleanAllInvalidBids: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-erc721Name}.
     */
    erc721Name(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * See {INFTKEYMarketPlaceV1-isListingAndBidEnabled}.
     */
    isListingAndBidEnabled(
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Enable to disable Bids and Listing
     */
    changeMarketplaceStatus: {
      (enabled: boolean, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        enabled: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        enabled: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        enabled: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-actionTimeOutRangeMin}.
     */
    actionTimeOutRangeMin(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * See {INFTKEYMarketPlaceV1-actionTimeOutRangeMax}.
     */
    actionTimeOutRangeMax(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * Change minimum listing and bid time range
     */
    changeMinActionTimeLimit: {
      (
        timeInSec: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        timeInSec: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        timeInSec: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        timeInSec: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Change maximum listing and bid time range
     */
    changeMaxActionTimeLimit: {
      (
        timeInSec: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        timeInSec: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        timeInSec: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        timeInSec: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * See {INFTKEYMarketPlaceV1-serviceFee}.
     */
    serviceFee(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN }>;

    /**
     * Change withdrawal fee percentage. If 1%, then input (1,100) If 0.5%, then input (5,1000)
     * @param feeBase_ Fraction of withdrawal fee base
     * @param feeFraction_ Fraction of withdrawal fee based on feeBase_
     */
    changeSeriveFee: {
      (
        feeFraction_: number | BN | string,
        feeBase_: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        feeFraction_: number | BN | string,
        feeBase_: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        feeFraction_: number | BN | string,
        feeBase_: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        feeFraction_: number | BN | string,
        feeBase_: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Set partner address and profit share
     * @param _partnerAddress Partner address
     * @param _partnerSharePercentage Fraction of withdrawal fee base
     */
    setPartnerAddressAndProfitShare: {
      (
        _partnerAddress: string,
        _partnerSharePercentage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _partnerAddress: string,
        _partnerSharePercentage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _partnerAddress: string,
        _partnerSharePercentage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _partnerAddress: string,
        _partnerSharePercentage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Change partner address
     * @param _partnerAddress Partner address Only partner can change their share address
     */
    changePartnerAddress: {
      (
        _partnerAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _partnerAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _partnerAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _partnerAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Propose partner share percentage
     * @param _partnerSharePercentage Partner proposed new share percentage
     */
    proposePartnerShareChange: {
      (
        _partnerSharePercentage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _partnerSharePercentage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _partnerSharePercentage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _partnerSharePercentage: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Accept partner share percentage proposal
     */
    acceptPartnerShareChange: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Reject partner share percentage proposal
     */
    rejectPartnerShareChange: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
